In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
df = pd.read_csv('../input/GroceryStoreDataSet.csv',names=['products'],header=None)
df

                          products
0               MILK,BREAD,BISCUIT
1    BREAD,MILK,BISCUIT,CORNFLAKES
2              BREAD,TEA,BOURNVITA
3             JAM,MAGGI,BREAD,MILK
4                MAGGI,TEA,BISCUIT
5              BREAD,TEA,BOURNVITA
6             MAGGI,TEA,CORNFLAKES
7          MAGGI,BREAD,TEA,BISCUIT
8              JAM,MAGGI,BREAD,TEA
9                       BREAD,MILK
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11  COFFEE,COCK,BISCUIT,CORNFLAKES
12          COFFEE,SUGER,BOURNVITA
13               BREAD,COFFEE,COCK
14             BREAD,SUGER,BISCUIT
15         COFFEE,SUGER,CORNFLAKES
16           BREAD,SUGER,BOURNVITA
17              BREAD,COFFEE,SUGER
18              BREAD,COFFEE,SUGER
19      TEA,MILK,COFFEE,CORNFLAKES

In [2]:
data = list(df["products"].apply(lambda x:x.split(',')))
te = TransactionEncoder()
te_data = te.fit(data).transform(data)
df = pd.DataFrame(te_data,columns=te.columns_)
df

    BISCUIT  BOURNVITA  BREAD   COCK  ...    MAGGI   MILK  SUGER    TEA
0      True      False   True  False  ...    False   True  False  False
1      True      False   True  False  ...    False   True  False  False
2     False       True   True  False  ...    False  False  False   True
3     False      False   True  False  ...     True   True  False  False
4      True      False  False  False  ...     True  False  False   True
5     False       True   True  False  ...    False  False  False   True
6     False      False  False  False  ...     True  False  False   True
7      True      False   True  False  ...     True  False  False   True
8     False      False   True  False  ...     True  False  False   True
9     False      False   True  False  ...    False   True  False  False
10     True      False  False   True  ...    False  False  False  False
11     True      False  False   True  ...    False  False  False  False
12    False       True  False  False  ...    False  False   True  False
13    False      False   True   True  ...    False  False  False  False
14     True      False   True  False  ...    False  False   True  False
15    False      False  False  False  ...    False  False   True  False
16    False       True   True  False  ...    False  False   True  False
17    False      False   True  False  ...    False  False   True  False
18    False      False   True  False  ...    False  False   True  False
19    False      False  False  False  ...    False   True  False   True

[20 rows x 11 columns]

In [3]:
df1 = apriori(df,min_support=0.01,use_colnames=True)
df1.sort_values(by="support",ascending=False)

    support                            itemsets
2      0.65                             (BREAD)
4      0.40                            (COFFEE)
0      0.35                           (BISCUIT)
10     0.35                               (TEA)
5      0.30                        (CORNFLAKES)
9      0.30                             (SUGER)
7      0.25                             (MAGGI)
8      0.25                              (MILK)
30     0.20                        (BREAD, TEA)
1      0.20                         (BOURNVITA)
28     0.20                       (MILK, BREAD)
35     0.20                     (COFFEE, SUGER)
29     0.20                      (SUGER, BREAD)
11     0.20                    (BREAD, BISCUIT)
33     0.20                (COFFEE, CORNFLAKES)
45     0.20                        (TEA, MAGGI)
14     0.15               (BISCUIT, CORNFLAKES)
31     0.15                      (COFFEE, COCK)
24     0.15                     (COFFEE, BREAD)
19     0.15                  (BREAD, BOURNVITA)
27     0.15                      (BREAD, MAGGI)
3      0.15                              (COCK)
40     0.10                   (TEA, CORNFLAKES)
58     0.10             (BREAD, BOURNVITA, TEA)
49     0.10              (MILK, BREAD, BISCUIT)
52     0.10             (COFFEE, BISCUIT, COCK)
53     0.10         (BISCUIT, COCK, CORNFLAKES)
54     0.10       (COFFEE, BISCUIT, CORNFLAKES)
56     0.10               (TEA, BISCUIT, MAGGI)
61     0.10              (COFFEE, SUGER, BREAD)
..      ...                                 ...
73     0.05            (TEA, MAGGI, CORNFLAKES)
74     0.05             (MILK, TEA, CORNFLAKES)
75     0.05                  (MILK, JAM, MAGGI)
76     0.05                   (JAM, TEA, MAGGI)
77     0.05  (MILK, BREAD, BISCUIT, CORNFLAKES)
78     0.05        (BREAD, TEA, BISCUIT, MAGGI)
80     0.05           (MILK, BREAD, JAM, MAGGI)
81     0.05            (BREAD, JAM, TEA, MAGGI)
72     0.05                 (MILK, TEA, COFFEE)
59     0.05          (COFFEE, SUGER, BOURNVITA)
62     0.05           (MILK, BREAD, CORNFLAKES)
60     0.05               (COFFEE, BREAD, COCK)
34     0.05                      (MILK, COFFEE)
39     0.05                 (SUGER, CORNFLAKES)
42     0.05                         (MILK, JAM)
43     0.05                          (JAM, TEA)
44     0.05                       (MILK, MAGGI)
25     0.05                 (BREAD, CORNFLAKES)
46     0.05                         (MILK, TEA)
47     0.05        (BREAD, BISCUIT, CORNFLAKES)
48     0.05             (BREAD, BISCUIT, MAGGI)
23     0.05                       (BREAD, COCK)
50     0.05             (SUGER, BISCUIT, BREAD)
51     0.05               (BREAD, TEA, BISCUIT)
20     0.05                 (COFFEE, BOURNVITA)
55     0.05         (MILK, BISCUIT, CORNFLAKES)
57     0.05           (BREAD, BOURNVITA, SUGER)
17     0.05                    (SUGER, BISCUIT)
37     0.05                 (MAGGI, CORNFLAKES)
82     0.05     (MILK, TEA, COFFEE, CORNFLAKES)

[83 rows x 2 columns]

In [4]:
assos = association_rules(df1, metric = "confidence", min_threshold = 0.3)
assos[assos['lift']>1]

                    antecedents    ...     conviction
2                        (COCK)    ...       1.950000
3                     (BISCUIT)    ...       1.225000
4                  (CORNFLAKES)    ...       1.300000
5                       (MAGGI)    ...       1.083333
6                        (MILK)    ...       1.083333
7                   (BOURNVITA)    ...       1.400000
8                       (SUGER)    ...       1.200000
9                   (BOURNVITA)    ...       1.400000
10                  (BOURNVITA)    ...       1.300000
13                        (JAM)    ...            inf
15                       (MILK)    ...       1.750000
16                      (BREAD)    ...       1.083333
17                      (SUGER)    ...       1.050000
18                      (BREAD)    ...       1.011111
21                     (COFFEE)    ...       1.360000
22                       (COCK)    ...            inf
23                       (COCK)    ...       2.100000
24                 (CORNFLAKES)    ...       1.275000
25                     (COFFEE)    ...       1.400000
26                 (CORNFLAKES)    ...       1.800000
27                     (COFFEE)    ...       1.400000
28                      (SUGER)    ...       1.800000
29                       (MILK)    ...       1.166667
30                 (CORNFLAKES)    ...       1.125000
32                        (JAM)    ...            inf
33                      (MAGGI)    ...       1.500000
34                        (JAM)    ...       1.500000
35                        (JAM)    ...       1.300000
36                        (TEA)    ...       1.750000
37                      (MAGGI)    ...       3.250000
..                          ...    ...            ...
153                      (COCK)    ...       2.700000
154                (CORNFLAKES)    ...       1.350000
155          (MILK, BREAD, JAM)    ...            inf
156        (MILK, BREAD, MAGGI)    ...            inf
157          (MILK, JAM, MAGGI)    ...            inf
158         (BREAD, JAM, MAGGI)    ...       1.500000
159                 (MILK, JAM)    ...            inf
160               (MILK, MAGGI)    ...            inf
161                (BREAD, JAM)    ...       1.900000
162              (BREAD, MAGGI)    ...       1.425000
163                (JAM, MAGGI)    ...       1.600000
164                       (JAM)    ...       1.900000
165           (BREAD, JAM, TEA)    ...            inf
166         (BREAD, JAM, MAGGI)    ...       1.300000
167         (BREAD, TEA, MAGGI)    ...       1.800000
168           (JAM, TEA, MAGGI)    ...            inf
169                (BREAD, JAM)    ...       1.600000
170              (BREAD, MAGGI)    ...       1.425000
171                  (JAM, TEA)    ...            inf
172                (JAM, MAGGI)    ...       1.600000
173                       (JAM)    ...       1.800000
174         (MILK, TEA, COFFEE)    ...            inf
175     (MILK, TEA, CORNFLAKES)    ...            inf
176  (MILK, COFFEE, CORNFLAKES)    ...            inf
177   (COFFEE, TEA, CORNFLAKES)    ...            inf
178                 (MILK, TEA)    ...            inf
179              (MILK, COFFEE)    ...            inf
180          (MILK, CORNFLAKES)    ...       1.900000
181               (COFFEE, TEA)    ...            inf
182           (TEA, CORNFLAKES)    ...       1.900000

[165 rows x 9 columns]